### ISSUE TITLE
Variable '${TEST_NAME}' not found

### ISSUE THREAD

**Issue by AnnaTanska** [sebastianciupinski/robotframework-autorecorder#10]
I would like each recording file to have a name that would be the same as TEST_NAME, but varaible ${TEST_NAME} is not recognized here
![image](https://github.com/user-attachments/assets/122074de-7d14-42a8-b6b3-28744487131f)
![image](https://github.com/user-attachments/assets/5694e6b4-632d-47dd-bbad-74b06438e561)
Is there anything I can do to make it easier to recognize recording files?

**Comment by sebastianciupinski** [comment]
@AnnaTanska - when you import library, tests are not executed yet, so variable ${TEST_NAME} does not exist yet. This is how RobotFramework works.
