### ISSUE TITLE
Hey I Can not record the screen it headless mode 

### ISSUE THREAD

**Issue by ghost** [sebastianciupinski/robotframework-autorecorder#2]
I am using headless mode of webdriver manager and i want to record the chrome window but its recording the system window so can you please tell me how can i achive that .
thanks

**Comment by sebastianciupinski** [comment]
@yogeshscn - by definition, when using headless mode there is no browser window, so there is nothing you can record. If you want to record execution, you need to not to use headless mode. This is problematic on headless environments, but using Xvfb (short for X virtual framebuffer) is a way to do that (on linux).

This RF library may help play with that: https://pypi.org/project/robotframework-xvfb/
On windows, there is desktop available through desktop integrtation services. At least it was when I was last time using windows for CI/CD jobs.
