### ISSUE TITLE
Problem with naming recording files

### ISSUE THREAD

**Issue by AnnaTanska** [sebastianciupinski/robotframework-autorecorder#7]
I use the AutoRecorder library, in the "name" parameter I enter my own name, but each recording file is named "recording_1", "recording_2" etc. Is there any way to change the name of the created file?
![image](https://github.com/user-attachments/assets/487467ae-4f23-4e26-9eba-19bfac7ecea0)

**Comment by sebastianciupinski** [comment]
Shall be fixed now: https://pypi.org/project/robotframework-autorecorder/0.1.6/

**Comment by sebastianciupinski** [comment]
@AnnaTanska shall be fixed now: https://pypi.org/project/robotframework-autorecorder/0.1.6/
